env: flex
service: search-api
runtime: nodejs

env_variables:
  GCLOUD_DATASTORE_NAMESPACE: test

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
 - npm-debug.log

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
