env: flex
service: search-api
runtime: nodejs

env_variables:
  GCLOUD_DATASTORE_NAMESPACE: test

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$
 - npm-debug.log

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  cool_down_period_sec: 120
